apiVersion: v1
kind: Pod
metadata:
  name: quote-server
  namespace: bootcamp
  labels:
    app: quote-server
spec:
  containers:
  - name: quote-server
    image: bobclarke/quote-server
    env:
    - name: MONGO_PORT
      value: "27017"
